### ISSUE TITLE
Upgrade ganache in docker images to the latest version

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/docker#127]
This ticket:
https://github.com/vegaprotocol/vega/issues/10954

requires us to make calls into Ethereum to determine the last finalized block on the chain. This is not supported in the version of ganache we currently use in our system tests. We need to upgrade to the latest version.

It looks like this work has been started:
https://github.com/vegaprotocol/docker/pull/99

**Comment by wwestgarth** [comment]
This has turned out to be a real pain.

The version that contains support for `eth_blockByNumber("finalized")` is `v.7.7.0`. 

Any newer build causes segfaults on `arm64`: https://github.com/trufflesuite/ganache/issues/4300#issuecomment-1464627269

BUT `v.7.7.0` has a bug in it which causes it to crash out during out system test runs:
```
eth_estimateGas
TypeError: Cannot read properties of undefined (reading 'gasEstimate')
    at /app/node_modules/ganache/dist/node/1.js:2:43466
    at /app/node_modules/ganache/dist/node/1.js:2:148181
    at exactimate (/app/node_modules/ganache/dist/node/1.js:2:147250)
```

This was fixed in ganache `v7.7.2`: https://github.com/trufflesuite/ganache/pull/4056

BUT then that version causes the above segfault on macs!

So the conclusion is that given the way we currently build out ganache-docker image there is no version that will work woth the system test that does not seg-fault on `arm64`.

The solution in https://github.com/trufflesuite/ganache/issues/4300#issuecomment-1464627269 suggests basing our image off their published image. Their image with the latest ganache _does_ work on `arm64`, but using it would involve reworking how we build our image with the pre-deployed smart-contracts in them.

Its a tangle.
